.TH 
	simple_shell man page

.SH NAME
	simple_shell (hsh.c \- line command interpreter in UNIX)

.SH SYNOPSIS
	$ /hsh [options] [file]
	
.SH DESCRIPTION
	simple_shell (hsh.c) is a UNIX command language interpreter that executes commands read from the standard input or from a file, made in C langage.

.B 
	./hsh	It's a simple UNIX command line interpreter.

.SH RETURN VALUE
	The program return the status of the last executed command ( 0 if no command was executed), the number means exit fail situation.
	
.SH PATH
	It search in the PATH env variable to find the executable program file location.

.SH EXAMPLES
.TS
center box tab(#);
l s s 
r | r c.
STANDARD INPUT LISTS
_
ls#list directory contents.
_
ls -l#List in long format file system type.
_
pwd# will display the present working directory.
_
rm# will remove a file.
_
mv# will move or rename one or more files or directories.
_
cp# Will copy SOURCE to DEST.
_
exit# cause normal process termination.
_
ctrl + d, ctrl + c# stop the prompt input.
.TE
	
.SH SEE ALSO
	
